apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdvorak-hello1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lojzalop/workshop3
    targetRevision: HEAD
    path: helm/hello

    helm:
      releaseName: hello1
      valueFiles:
        - ../myvalues.yml

  destination:
    name: in-cluster
    namespace: mdvorak
